### ISSUE TITLE
Issue with webpack

### ISSUE THREAD

**Issue by chevdor** [ConsenSys/truffle-solidity-loader#4] opened 2016-10-03 15:55 UTC
Following: http://truffleframework.com/tutorials/bundling-with-webpack

I am running in the following error:

```
ERROR in Cannot find module 'truffle/lib/contracts'
 @ ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/ContractPage.vue 15:25-70
```

as soon as I use:
`import Contract from '../contracts/Contract.sol'`

I can confirm that the location is fine and '../contracts/Contract.sol' is found.
It sounds like a missing dependency at https://github.com/ConsenSys/truffle-solidity-loader/blob/master/index.js#L2

**Comment by tcoulter** [comment] 2016-10-03 16:43
Hey @chevdor - we need to update our docs. Your project needs to have `truffle` installed locally as a dependency. So within your project folder run `npm install truffle --save`.

Eventually, truffle will be broken up into two modules, `truffle` and `truffle-cli`, such that the core truffle code will be a part of your project, and the command line utility will be a standalone module installed globally. This allows you to "pin" a version of Truffle to your project to more easily maintain dependencies across projects.

**Comment by jmdfm** [comment] 2016-10-03 18:16
The issue is that `truffle` is in `devDependencies` instead of `dependencies` in the `package.json` right now

**Comment by jmdfm** [comment] 2016-10-03 18:25
Fixed in 06ba159430c2bfab834ad59c70e56184737ca0c4

**Comment by jmdfm** [comment] 2016-10-03 18:26
Pushed 0.0.3 to `npm`

**Closed as completed by jmdfm** 2016-10-03 18:25 UTC

**Comment by chevdor** [comment] 2016-10-03 22:36
That was fast, thank you all!
Indeed `npm install truffle --save` fixed the current issue.
